// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentCreateParams = { id: string, name?: string | null, description?: string | null, extends?: string | null, agentDir?: string | null, };
