// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentInfo = {
  id: string;
  name: string | null;
  description: string | null;
  configFile: string | null;
  nicknameCandidates: Array<string> | null;
  workspace: string | null;
  extends: string | null;
  hasWorkspace: boolean;
};
