// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentContactsConfig } from "./AgentContactsConfig";
import type { AgentToolsConfig } from "./AgentToolsConfig";
import type { AskForApproval } from "./AskForApproval";
import type { SandboxMode } from "./SandboxMode";

export type AgentUpdateParams = { id: string, cwd?: string | null, agentDir?: string | null, name: string | null, description: string | null, model: string | null, approvalPolicy?: AskForApproval | null, sandboxMode?: SandboxMode | null, developerInstructions: string | null, nicknameCandidates: Array<string> | null, extends?: string | null, workspace?: string | null, tools: AgentToolsConfig | null, skills?: Array<string> | null, contacts?: AgentContactsConfig | null, };
