// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentUpdateParams = {
  id: string;
  agentDir?: string | null;
  name?: string | null;
  description?: string | null;
  model?: string | null;
  developerInstructions?: string | null;
  nicknameCandidates?: Array<string> | null;
  extends?: string | null;
  workspace?: string | null;
  tools?: AgentToolsConfig | null;
  skills?: Array<string> | null;
};

export type AgentToolsConfig = {
  allow?: Array<string> | null;
  deny?: Array<string> | null;
};
