// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentToolsConfig = {
  allow: Array<string> | null;
  deny: Array<string> | null;
};
