// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

export type AgentReadResponse = {
  id: string;
  name: string | null;
  description: string | null;
  configFile: string | null;
  nicknameCandidates: Array<string> | null;
  workspace: string | null;
  config: JsonValue;
  model: string | null;
  developerInstructions: string | null;
  extends: string | null;
  hasWorkspace: boolean;
  workspaceInstructions: string | null;
  tools: AgentToolsConfig | null;
  skills: Array<string> | null;
};

export type AgentToolsConfig = {
  allow?: Array<string> | null;
  deny?: Array<string> | null;
};
