// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigProviderInfo } from "./ConfigProviderInfo";

export type ConfigProvidersResponse = { providers: { [key in string]?: ConfigProviderInfo }, };
