// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadTurnQueueItem } from "./ThreadTurnQueueItem";

export type ThreadTurnQueueDeleteResponse = { threadId: string, queue: Array<ThreadTurnQueueItem>, };
